//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class gradeInfo
    {
        public int studentId { get; set; }
        public string courseNumber { get; set; }
        public string courseTitle { get; set; }
        public Nullable<float> hp { get; set; }
        public string coursePeriod { get; set; }
        public string studentName { get; set; }
        public string email { get; set; }
        public Nullable<int> grade { get; set; }
    }
}
